### ISSUE TITLE
Unable to Process AssemblyInfo.cs

### ISSUE THREAD

**Issue by Phlorgian** [DanielTheCoder/msbuild.templates#1]
For every MSBuild project I try creating with this add-on, I cannot process the AssemblyInfo.cs file.  I get blank properties in properties designer.  When I fill those properties in and attempt to save that assembly info, I am always greeted with the error,

"The property could not be read/written because the language service returned an unknown error."

Even if I create an AssemblyInfo.cs file by hand, the properties will not load and the same error will result if I attempt to save new values.

**Comment by DanielTheCoder** [comment]
Why are you trying to add an AssemblyInfo.cs file or adding version information to this kind of projects?
